version: '3.9'

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    #- ./drive:/drive:rw
    #- ./record:/record:rw
    - type: bind
        source: /home/pi/DockerFile/Guacamole/drive:rw
        target: ./drive
    - type: bind
        source: /home/pi/DockerFile/Guacamole/record:rw
        target: ./record
    deploy:
      placement:
        constraints:
          - "node.labels.name==cbridge"
  # postgres
  postgres:
    #container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'Watashi'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4-buster
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    #- ./init:/docker-entrypoint-initdb.d:z
    #- ./data:/var/lib/postgresql/data:Z
    - type: bind
        source: /home/pi/DockerFile/Guacamole/docker-entrypoint-initdb.d:z
        target: ./init
    - type: bind
        source: /home/pi/DockerFile/Guacamole/var/lib/postgresql/data:Z
        target: ./data
    deploy:
      placement:
        constraints:
          - "node.labels.name==cbridge"
  # guacamole
  guacamole:
    container_name: guacamole_compose
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'Watashi'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnetwork_compose:
    ports:
## enable next line if not using nginx
##    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
    - 8080/tcp
    restart: always
    deploy:
      placement:
        constraints:
          - "node.labels.name==cbridge"
########### optional ##############
  # nginx
  nginx:
   #container_name: nginx_guacamole_compose
   restart: always
   image: nginx
   volumes:
   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./nginx/mysite.template:/etc/nginx/conf.d/default.conf:ro
   deploy:
     placement:
       constraints:
          - "node.labels.name==cbridge"
   ports:
   - 8443:443
   links:
   - guacamole
   networks:
     guacnetwork_compose:
   # run nginx
   command: /bin/bash -c "nginx -g 'daemon off;'"
# nginx-debug-mode
#   command: /bin/bash -c "nginx-debug -g 'daemon off;'"
####################################################################################
