version: '3.9'
services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - 19132:19132/udp
    volumes:
      - bds:/data

    stdin_open: true
    tty: true
    deploy:
      placement:
        constraints:
          - "node.labels.name==HomeComputer"
    
  
volumes:
  bds: {}