version: "3.9"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole #no longer supported
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "1010:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: 'Watashi'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/pi/Desktop/ClusterHatConfigs/DockerData/PiHole/etc'
      - '/home/pi/Desktop/ClusterHatConfigs/DockerData/PiHole/dnsmasq'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    
    deploy:
      placement:
        constraints:
          - "node==p4"

